export const routes = {
  landing: '/',
  login: '/login',
  register: '/register',
  home: '/workspace',
  upload: '/workspace/upload',
  extraction: '/workspace/extraction/:resumeId',
  dashboard: '/workspace/dashboard/:resumeId',
  links: '/workspace/links/:resumeId',
  roadmap: '/workspace/roadmap/:resumeId',
  builder: '/workspace/builder/:resumeId',
  interviewLobby: '/workspace/interview',
  interviewRoom: '/workspace/interview/:roomName',
  interviewReport: '/workspace/interview/:roomName/report',
  admin: '/admin',
  adminCandidates: '/admin/candidates',
  adminCandidateDetail: '/admin/candidates/:candidateId',
  adminBulk: '/admin/bulk-upload',
  adminSearch: '/admin/search',
  adminInterviews: '/admin/interviews',
  adminReports: '/admin/reports',
  adminPipeline: '/admin/pipeline',
  adminCompare: '/admin/compare',
  adminUsers: '/admin/users',
  adminMonitoring: '/admin/monitoring',
  adminSettings: '/admin/settings',
}
